Refactors `settings::RuleStrategy.rule` as `Rule` enum
kubewarden/user-group-psp-policy pull request #56
Opened 2023-04-25 16:19 UTC by geeksambhu

## Description

Fix https://github.com/kubewarden/user-group-psp-policy/issues/16

## Test

To test this pull request, you can run the following commands:

## Additional Information

### Tradeoff

### Potential improvement

2023-04-26 13:52 UTC, jvanz requested changes
That's good starting point Shiva! However, I have some change requests.

In the Rust code you can remove the `ranges` field in the `RuleStrategy` struct. Now the ranges will be inside the `Rule` enum. Making the `ranges` field obsolete. This means that you can also simplify the code where the validations are performed. 

Once you remove the `ranges` field, another problem comes up.  The settings will serialize as the following:

```json
{
  "run_as_user": {
    "rule": {
      "MustRunAs": [
        {
          "min": 1000,
          "max": 2000
        }
      ]
    },
    "overwrite": true
  },
  "run_as_group": {
    "rule": "RunAsAny",
    "overwrite": false
  },
  "supplemental_groups": {
    "rule": "RunAsAny",
    "overwrite": false
  }
}
```

Now, take a look how the stable version is serialized (you can see more examples in the README):

```json
{
  "run_as_user": {
    "rule": "RunAsAny"
  },
  "run_as_group": {
    "rule": "MayRunAs",
    "ranges": [
      {
        "min": 1000,
        "max": 2000
      },
      {
        "min": 2001,
        "max": 3000
      }
    ]
  },
  "supplemental_groups":{
    "rule": "MayRunAs",
    "ranges": [
      {
        "min": 1000,
        "max": 2000
      },
      {
        "min": 2001,
        "max": 3000
      }
    ]
  }
}
```

Note this will require a major version update. I'm not sure if this should be the case. Therefore, I would say to research if you can get the same JSON as in the stable version changing serde configs or customize the way serde serialize/deserialize the object.  See the serde [docs](https://serde.rs/custom-serialization.html) to see how to do that.

Note, the serialization/deserialization customization may not require the change in the internal struct representation. If you think this will be required, let us know.

2023-05-03 16:03 UTC, viccuad commented
After consideration, I think that doing the checks via the deserializer makes everything needlessly complicated. The card did indeed ask to try to do it via de Deserializer, which I know think it's a wrong approach. I'm sorry for that.

I would be happy just having

```
pub(crate) struct RuleStrategy {
    pub rule: Rule,
    pub ranges: Vec<IDRange>,
    pub overwrite: bool,
}
```

Where `Rule` is an enum with variants `MustRunAs`, `RunAsAny`, `MustRunAsNonRoot`, `MayRunAs` (with the correct serde attributes for it to deserialize correctly). And having the validation of the settings being performed on runtime at `validate()`.

2023-05-16 10:26 UTC, viccuad commented on src/settings.rs
> +                    rule: Rule::MustRunAs,
I think this is incorrect, shouldn't it be `rule: rule`, as in line 237?

On line 226, we iterate through all allowed rules values, and we create to possible settings, one where we change the `run_as_group`, and one where we change the `supplemental_groups`.

2023-05-16 10:27 UTC, viccuad commented on src/settings.rs
> +    #[serde(rename = "MustRunAs")]
we can drop all serde renames, they aren't needed, they set the same style as the enum variants already have.

2023-05-16 10:45 UTC, viccuad approved these changes
LGTM!

2023-05-16 10:45 UTC, merged

2023-05-16 10:46 UTC, viccuad commented
tagged in main as `v0.4.8`, will be released shortly.